platform :ios, '9.0'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#use_frameworks!

target 'WRGJ.JProduct' do
 #use_frameworks!

pod "AFNetworking",     "~> 3.1.0"
pod "MBProgressHUD"
pod 'SDCycleScrollView'

end
